name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secrets (safe)
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Token: ${{ secrets.DOCKER_TOKEN != '' && 'Token is set' || 'Token is empty' }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mamedaliii/nginx-custom:latest
